{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n",
      "No path specified. Models will be saved in: \"AutogluonModels/ag-20240709_183812\"\n",
      "Verbosity: 2 (Standard Logging)\n",
      "=================== System Info ===================\n",
      "AutoGluon Version:  1.1.1\n",
      "Python Version:     3.10.14\n",
      "Operating System:   Linux\n",
      "Platform Machine:   x86_64\n",
      "Platform Version:   #1 SMP Fri Mar 29 23:14:13 UTC 2024\n",
      "CPU Count:          12\n",
      "Memory Avail:       4.71 GB / 7.69 GB (61.2%)\n",
      "Disk Space Avail:   206.21 GB / 465.76 GB (44.3%)\n",
      "===================================================\n",
      "Presets specified: ['best_quality']\n",
      "Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)\n",
      "Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=5, num_bag_sets=1\n",
      "DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.\n",
      "\tThis is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.\n",
      "\tRunning DyStack for up to 15s of the 60s of remaining time (25%).\n",
      "2024-07-09 21:38:22,102\tINFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.\n",
      "\tRunning DyStack sub-fit in a ray process to avoid memory leakage. Enabling ray logging (enable_ray_logging=True). Specify `ds_args={'enable_ray_logging': False}` if you experience logging issues.\n",
      "/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/tabular/predictor/predictor.py:1242: UserWarning: Failed to use ray for memory safe fits. Falling back to normal fit. Error: UnicodeDecodeError('utf-8', b'\\xf8\\x95\\xa0\\x81\\x8e\\xf8\\x91\\x80\\x81\\x89\\xf8\\x90\\x90\\x81\\x89\\xf8\\x91\\xb0\\x80\\xa0\\xf8\\x91\\xa0\\x81\\xa5\\xf8\\x9c\\xa0\\x81\\xaf\\xf8\\x99\\x90\\x81\\xa3\\xf8\\x91\\xb0\\x80\\xa0\\xf8\\x96\\x80\\x81\\x94\\xf8\\x8c\\x90\\x80\\xa0\\xf8\\x8d\\x90\\x80\\xb6\\xf8\\x88\\x80\\x80\\xb0', 0, 1, 'invalid start byte')\n",
      "  stacked_overfitting = self._sub_fit_memory_save_wrapper(\n",
      "Warning: Not enough time to fit DyStack! Skipping...\n",
      "\t1\t = Optimal   num_stack_levels (Stacked Overfitting Occurred: False)\n",
      "\t21s\t = DyStack   runtime |\t39s\t = Remaining runtime\n",
      "Starting main fit with num_stack_levels=1.\n",
      "\tFor future fit calls on this dataset, you can skip DyStack to save time: `predictor.fit(..., dynamic_stacking=False, num_stack_levels=1)`\n",
      "Beginning AutoGluon training ... Time limit = 39s\n",
      "AutoGluon will save models to \"AutogluonModels/ag-20240709_183812\"\n",
      "Train Data Rows:    4\n",
      "Train Data Columns: 2\n",
      "Label Column:       target\n",
      "Problem Type:       binary\n",
      "Preprocessing data ...\n",
      "Warning: Updated label_count_threshold from 10 to 2 to avoid cutting too many classes.\n",
      "Warning: Updated holdout_frac from 0.2 to 0.251 to avoid cutting too many classes.\n",
      "Warning: Updated num_bag_folds from 5 to 4 to avoid cutting too many classes.\n",
      "Selected class <--> label mapping:  class 1 = 1, class 0 = 0\n",
      "Using Feature Generators to preprocess the data ...\n",
      "Fitting AutoMLPipelineFeatureGenerator...\n",
      "\tAvailable Memory:                    4400.35 MB\n",
      "\tTrain Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)\n",
      "\tInferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.\n",
      "\tStage 1 Generators:\n",
      "\t\tFitting AsTypeFeatureGenerator...\n",
      "\tStage 2 Generators:\n",
      "\t\tFitting FillNaFeatureGenerator...\n",
      "\tStage 3 Generators:\n",
      "\t\tFitting IdentityFeatureGenerator...\n",
      "\tStage 4 Generators:\n",
      "\t\tFitting DropUniqueFeatureGenerator...\n",
      "\tStage 5 Generators:\n",
      "\t\tFitting DropDuplicatesFeatureGenerator...\n",
      "\tTypes of features in original data (raw dtype, special dtypes):\n",
      "\t\t('int', []) : 2 | ['num', 'amount']\n",
      "\tTypes of features in processed data (raw dtype, special dtypes):\n",
      "\t\t('int', []) : 2 | ['num', 'amount']\n",
      "\t0.0s = Fit runtime\n",
      "\t2 features in original data used to generate 2 features in processed data.\n",
      "\tTrain Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)\n",
      "Data preprocessing and feature engineering runtime = 0.19s ...\n",
      "AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'\n",
      "\tTo change this, specify the eval_metric parameter of Predictor()\n",
      "Large model count detected (112 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.\n",
      "User-specified model hyperparameters to be fit:\n",
      "{\n",
      "\t'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],\n",
      "\t'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],\n",
      "\t'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],\n",
      "\t'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],\n",
      "\t'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],\n",
      "\t'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],\n",
      "\t'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],\n",
      "\t'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],\n",
      "}\n",
      "AutoGluon will fit 2 stack levels (L1 to L2) ...\n",
      "Fitting 110 L1 models ...\n",
      "Fitting model: KNeighborsUnif_BAG_L1 ... Training model for up to 26.03s of the 39.04s of remaining time.\n",
      "\tWarning: Exception caused KNeighborsUnif_BAG_L1 to fail during training... Skipping this model.\n",
      "\t\tExpected n_neighbors < n_samples_fit, but n_neighbors = 5, n_samples_fit = 4, n_samples = 4\n",
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1904, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1844, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 856, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 165, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 263, in _fit\n",
      "    self._fit_single(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 534, in _fit_single\n",
      "    self._oof_pred_proba = model_base.predict_proba_oof(X=X_fit, y=y_fit)[: len(X)]\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/tabular/models/knn/knn_model.py\", line 120, in predict_proba_oof\n",
      "    y_oof_pred_proba = self._predict_proba_oof(X=X, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/tabular/models/knn/knn_model.py\", line 132, in _predict_proba_oof\n",
      "    y_oof_pred_proba = KNeighborsClassifierLOOMixin.predict_proba_loo(self.model)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/tabular/models/knn/_knn_loo_variants.py\", line 68, in predict_proba_loo\n",
      "    neigh_dist, neigh_ind = self.kneighbors()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/sklearn/neighbors/_base.py\", line 835, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors < n_samples_fit, but n_neighbors = 5, n_samples_fit = 4, n_samples = 4\n",
      "Fitting model: KNeighborsDist_BAG_L1 ... Training model for up to 25.76s of the 38.77s of remaining time.\n",
      "\tWarning: Exception caused KNeighborsDist_BAG_L1 to fail during training... Skipping this model.\n",
      "\t\tExpected n_neighbors < n_samples_fit, but n_neighbors = 5, n_samples_fit = 4, n_samples = 4\n",
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1904, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1844, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 856, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 165, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 263, in _fit\n",
      "    self._fit_single(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 534, in _fit_single\n",
      "    self._oof_pred_proba = model_base.predict_proba_oof(X=X_fit, y=y_fit)[: len(X)]\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/tabular/models/knn/knn_model.py\", line 120, in predict_proba_oof\n",
      "    y_oof_pred_proba = self._predict_proba_oof(X=X, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/tabular/models/knn/knn_model.py\", line 132, in _predict_proba_oof\n",
      "    y_oof_pred_proba = KNeighborsClassifierLOOMixin.predict_proba_loo(self.model)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/tabular/models/knn/_knn_loo_variants.py\", line 68, in predict_proba_loo\n",
      "    neigh_dist, neigh_ind = self.kneighbors()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/sklearn/neighbors/_base.py\", line 835, in kneighbors\n",
      "    raise ValueError(\n",
      "ValueError: Expected n_neighbors < n_samples_fit, but n_neighbors = 5, n_samples_fit = 4, n_samples = 4\n",
      "Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 25.67s of the 38.68s of remaining time.\n",
      "\tFitting 4 child models (S1F1 - S1F4) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=3, gpus=0, memory=0.01%)\n",
      "\tWarning: Exception caused LightGBMXT_BAG_L1 to fail during training... Skipping this model.\n",
      "\t\t'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1904, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1844, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 856, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 165, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 288, in _fit\n",
      "    self._fit_folds(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 714, in _fit_folds\n",
      "    fold_fitting_strategy.after_all_folds_scheduled()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 651, in after_all_folds_scheduled\n",
      "    self.ray.init(**ray_init_args)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/worker.py\", line 1645, in init\n",
      "    _global_node = ray._private.node.Node(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 315, in __init__\n",
      "    self.start_ray_processes()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 1372, in start_ray_processes\n",
      "    resource_spec = self.get_resource_spec()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 550, in get_resource_spec\n",
      "    self._resource_spec = ResourceSpec(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/resource_spec.py\", line 215, in resolve\n",
      "    accelerator_manager.get_current_node_accelerator_type()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/accelerators/nvidia_gpu.py\", line 71, in get_current_node_accelerator_type\n",
      "    device_name = device_name.decode(\"utf-8\")\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Fitting model: LightGBM_BAG_L1 ... Training model for up to 23.51s of the 36.52s of remaining time.\n",
      "\tFitting 4 child models (S1F1 - S1F4) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=3, gpus=0, memory=0.01%)\n",
      "\tWarning: Exception caused LightGBM_BAG_L1 to fail during training... Skipping this model.\n",
      "\t\t'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1904, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1844, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 856, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 165, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 288, in _fit\n",
      "    self._fit_folds(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 714, in _fit_folds\n",
      "    fold_fitting_strategy.after_all_folds_scheduled()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 651, in after_all_folds_scheduled\n",
      "    self.ray.init(**ray_init_args)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/worker.py\", line 1645, in init\n",
      "    _global_node = ray._private.node.Node(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 315, in __init__\n",
      "    self.start_ray_processes()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 1372, in start_ray_processes\n",
      "    resource_spec = self.get_resource_spec()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 550, in get_resource_spec\n",
      "    self._resource_spec = ResourceSpec(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/resource_spec.py\", line 215, in resolve\n",
      "    accelerator_manager.get_current_node_accelerator_type()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/accelerators/nvidia_gpu.py\", line 71, in get_current_node_accelerator_type\n",
      "    device_name = device_name.decode(\"utf-8\")\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Fitting model: RandomForestGini_BAG_L1 ... Training model for up to 21.53s of the 34.54s of remaining time.\n",
      "\t0.0\t = Validation score   (accuracy)\n",
      "\t0.92s\t = Training   runtime\n",
      "\t0.08s\t = Validation runtime\n",
      "Fitting model: RandomForestEntr_BAG_L1 ... Training model for up to 20.45s of the 33.46s of remaining time.\n",
      "\t0.0\t = Validation score   (accuracy)\n",
      "\t0.56s\t = Training   runtime\n",
      "\t0.07s\t = Validation runtime\n",
      "Fitting model: CatBoost_BAG_L1 ... Training model for up to 19.74s of the 32.75s of remaining time.\n",
      "\tFitting 4 child models (S1F1 - S1F4) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=3, gpus=0, memory=0.02%)\n",
      "\tWarning: Exception caused CatBoost_BAG_L1 to fail during training... Skipping this model.\n",
      "\t\t'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1904, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1844, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 856, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 165, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 288, in _fit\n",
      "    self._fit_folds(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 714, in _fit_folds\n",
      "    fold_fitting_strategy.after_all_folds_scheduled()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 651, in after_all_folds_scheduled\n",
      "    self.ray.init(**ray_init_args)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/worker.py\", line 1645, in init\n",
      "    _global_node = ray._private.node.Node(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 315, in __init__\n",
      "    self.start_ray_processes()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 1372, in start_ray_processes\n",
      "    resource_spec = self.get_resource_spec()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 550, in get_resource_spec\n",
      "    self._resource_spec = ResourceSpec(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/resource_spec.py\", line 215, in resolve\n",
      "    accelerator_manager.get_current_node_accelerator_type()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/accelerators/nvidia_gpu.py\", line 71, in get_current_node_accelerator_type\n",
      "    device_name = device_name.decode(\"utf-8\")\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Fitting model: ExtraTreesGini_BAG_L1 ... Training model for up to 17.65s of the 30.66s of remaining time.\n",
      "\t0.0\t = Validation score   (accuracy)\n",
      "\t0.6s\t = Training   runtime\n",
      "\t0.07s\t = Validation runtime\n",
      "Fitting model: ExtraTreesEntr_BAG_L1 ... Training model for up to 16.77s of the 29.78s of remaining time.\n",
      "\t0.0\t = Validation score   (accuracy)\n",
      "\t0.69s\t = Training   runtime\n",
      "\t0.07s\t = Validation runtime\n",
      "Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 15.67s of the 28.68s of remaining time.\n",
      "\tFitting 4 child models (S1F1 - S1F4) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=3, gpus=0, memory=0.00%)\n",
      "\tWarning: Exception caused NeuralNetFastAI_BAG_L1 to fail during training... Skipping this model.\n",
      "\t\t'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1904, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1844, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 856, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 165, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 288, in _fit\n",
      "    self._fit_folds(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 714, in _fit_folds\n",
      "    fold_fitting_strategy.after_all_folds_scheduled()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 651, in after_all_folds_scheduled\n",
      "    self.ray.init(**ray_init_args)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/worker.py\", line 1645, in init\n",
      "    _global_node = ray._private.node.Node(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 315, in __init__\n",
      "    self.start_ray_processes()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 1372, in start_ray_processes\n",
      "    resource_spec = self.get_resource_spec()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 550, in get_resource_spec\n",
      "    self._resource_spec = ResourceSpec(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/resource_spec.py\", line 215, in resolve\n",
      "    accelerator_manager.get_current_node_accelerator_type()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/accelerators/nvidia_gpu.py\", line 71, in get_current_node_accelerator_type\n",
      "    device_name = device_name.decode(\"utf-8\")\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Fitting model: XGBoost_BAG_L1 ... Training model for up to 13.5s of the 26.51s of remaining time.\n",
      "\tFitting 4 child models (S1F1 - S1F4) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=3, gpus=0, memory=0.04%)\n",
      "\tWarning: Exception caused XGBoost_BAG_L1 to fail during training... Skipping this model.\n",
      "\t\t'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1904, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1844, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 856, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 165, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 288, in _fit\n",
      "    self._fit_folds(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 714, in _fit_folds\n",
      "    fold_fitting_strategy.after_all_folds_scheduled()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 651, in after_all_folds_scheduled\n",
      "    self.ray.init(**ray_init_args)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/worker.py\", line 1645, in init\n",
      "    _global_node = ray._private.node.Node(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 315, in __init__\n",
      "    self.start_ray_processes()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 1372, in start_ray_processes\n",
      "    resource_spec = self.get_resource_spec()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 550, in get_resource_spec\n",
      "    self._resource_spec = ResourceSpec(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/resource_spec.py\", line 215, in resolve\n",
      "    accelerator_manager.get_current_node_accelerator_type()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/accelerators/nvidia_gpu.py\", line 71, in get_current_node_accelerator_type\n",
      "    device_name = device_name.decode(\"utf-8\")\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 10.7s of the 23.71s of remaining time.\n",
      "\tFitting 4 child models (S1F1 - S1F4) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=3, gpus=0, memory=0.00%)\n",
      "\tWarning: Exception caused NeuralNetTorch_BAG_L1 to fail during training... Skipping this model.\n",
      "\t\t'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1904, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1844, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 856, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 165, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 288, in _fit\n",
      "    self._fit_folds(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 714, in _fit_folds\n",
      "    fold_fitting_strategy.after_all_folds_scheduled()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 651, in after_all_folds_scheduled\n",
      "    self.ray.init(**ray_init_args)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/worker.py\", line 1645, in init\n",
      "    _global_node = ray._private.node.Node(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 315, in __init__\n",
      "    self.start_ray_processes()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 1372, in start_ray_processes\n",
      "    resource_spec = self.get_resource_spec()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 550, in get_resource_spec\n",
      "    self._resource_spec = ResourceSpec(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/resource_spec.py\", line 215, in resolve\n",
      "    accelerator_manager.get_current_node_accelerator_type()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/accelerators/nvidia_gpu.py\", line 71, in get_current_node_accelerator_type\n",
      "    device_name = device_name.decode(\"utf-8\")\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 8.37s of the 21.38s of remaining time.\n",
      "\tFitting 4 child models (S1F1 - S1F4) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=3, gpus=0, memory=0.13%)\n",
      "\tWarning: Exception caused LightGBMLarge_BAG_L1 to fail during training... Skipping this model.\n",
      "\t\t'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1904, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1844, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 856, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 165, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 288, in _fit\n",
      "    self._fit_folds(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 714, in _fit_folds\n",
      "    fold_fitting_strategy.after_all_folds_scheduled()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 651, in after_all_folds_scheduled\n",
      "    self.ray.init(**ray_init_args)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/worker.py\", line 1645, in init\n",
      "    _global_node = ray._private.node.Node(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 315, in __init__\n",
      "    self.start_ray_processes()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 1372, in start_ray_processes\n",
      "    resource_spec = self.get_resource_spec()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 550, in get_resource_spec\n",
      "    self._resource_spec = ResourceSpec(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/resource_spec.py\", line 215, in resolve\n",
      "    accelerator_manager.get_current_node_accelerator_type()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/accelerators/nvidia_gpu.py\", line 71, in get_current_node_accelerator_type\n",
      "    device_name = device_name.decode(\"utf-8\")\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Fitting model: CatBoost_r177_BAG_L1 ... Training model for up to 6.04s of the 19.05s of remaining time.\n",
      "\tFitting 4 child models (S1F1 - S1F4) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=3, gpus=0, memory=0.08%)\n",
      "\tWarning: Exception caused CatBoost_r177_BAG_L1 to fail during training... Skipping this model.\n",
      "\t\t'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1904, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1844, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 856, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 165, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 288, in _fit\n",
      "    self._fit_folds(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 714, in _fit_folds\n",
      "    fold_fitting_strategy.after_all_folds_scheduled()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 651, in after_all_folds_scheduled\n",
      "    self.ray.init(**ray_init_args)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/worker.py\", line 1645, in init\n",
      "    _global_node = ray._private.node.Node(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 315, in __init__\n",
      "    self.start_ray_processes()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 1372, in start_ray_processes\n",
      "    resource_spec = self.get_resource_spec()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 550, in get_resource_spec\n",
      "    self._resource_spec = ResourceSpec(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/resource_spec.py\", line 215, in resolve\n",
      "    accelerator_manager.get_current_node_accelerator_type()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/accelerators/nvidia_gpu.py\", line 71, in get_current_node_accelerator_type\n",
      "    device_name = device_name.decode(\"utf-8\")\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Fitting model: NeuralNetTorch_r79_BAG_L1 ... Training model for up to 3.82s of the 16.83s of remaining time.\n",
      "\tFitting 4 child models (S1F1 - S1F4) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=3, gpus=0, memory=0.00%)\n",
      "\tWarning: Exception caused NeuralNetTorch_r79_BAG_L1 to fail during training... Skipping this model.\n",
      "\t\t'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1904, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1844, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 856, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 165, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 288, in _fit\n",
      "    self._fit_folds(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 714, in _fit_folds\n",
      "    fold_fitting_strategy.after_all_folds_scheduled()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 651, in after_all_folds_scheduled\n",
      "    self.ray.init(**ray_init_args)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/worker.py\", line 1645, in init\n",
      "    _global_node = ray._private.node.Node(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 315, in __init__\n",
      "    self.start_ray_processes()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 1372, in start_ray_processes\n",
      "    resource_spec = self.get_resource_spec()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 550, in get_resource_spec\n",
      "    self._resource_spec = ResourceSpec(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/resource_spec.py\", line 215, in resolve\n",
      "    accelerator_manager.get_current_node_accelerator_type()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/accelerators/nvidia_gpu.py\", line 71, in get_current_node_accelerator_type\n",
      "    device_name = device_name.decode(\"utf-8\")\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Fitting model: LightGBM_r131_BAG_L1 ... Training model for up to 0.78s of the 13.79s of remaining time.\n",
      "\tFitting 4 child models (S1F1 - S1F4) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=3, gpus=0, memory=0.10%)\n",
      "\tWarning: Exception caused LightGBM_r131_BAG_L1 to fail during training... Skipping this model.\n",
      "\t\t'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1904, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1844, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 856, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 165, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 288, in _fit\n",
      "    self._fit_folds(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 714, in _fit_folds\n",
      "    fold_fitting_strategy.after_all_folds_scheduled()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 651, in after_all_folds_scheduled\n",
      "    self.ray.init(**ray_init_args)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/worker.py\", line 1645, in init\n",
      "    _global_node = ray._private.node.Node(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 315, in __init__\n",
      "    self.start_ray_processes()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 1372, in start_ray_processes\n",
      "    resource_spec = self.get_resource_spec()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 550, in get_resource_spec\n",
      "    self._resource_spec = ResourceSpec(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/resource_spec.py\", line 215, in resolve\n",
      "    accelerator_manager.get_current_node_accelerator_type()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/accelerators/nvidia_gpu.py\", line 71, in get_current_node_accelerator_type\n",
      "    device_name = device_name.decode(\"utf-8\")\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Fitting model: WeightedEnsemble_L2 ... Training model for up to 39.05s of the 9.62s of remaining time.\n",
      "\tEnsemble Weights: {'RandomForestGini_BAG_L1': 1.0}\n",
      "\t0.0\t = Validation score   (accuracy)\n",
      "\t0.1s\t = Training   runtime\n",
      "\t0.0s\t = Validation runtime\n",
      "Fitting 108 L2 models ...\n",
      "Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 9.44s of the 9.4s of remaining time.\n",
      "\tFitting 4 child models (S1F1 - S1F4) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=3, gpus=0, memory=0.25%)\n",
      "\tWarning: Exception caused LightGBMXT_BAG_L2 to fail during training... Skipping this model.\n",
      "\t\t'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1904, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1844, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 856, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 165, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 288, in _fit\n",
      "    self._fit_folds(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 714, in _fit_folds\n",
      "    fold_fitting_strategy.after_all_folds_scheduled()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 651, in after_all_folds_scheduled\n",
      "    self.ray.init(**ray_init_args)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/worker.py\", line 1645, in init\n",
      "    _global_node = ray._private.node.Node(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 315, in __init__\n",
      "    self.start_ray_processes()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 1372, in start_ray_processes\n",
      "    resource_spec = self.get_resource_spec()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 550, in get_resource_spec\n",
      "    self._resource_spec = ResourceSpec(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/resource_spec.py\", line 215, in resolve\n",
      "    accelerator_manager.get_current_node_accelerator_type()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/accelerators/nvidia_gpu.py\", line 71, in get_current_node_accelerator_type\n",
      "    device_name = device_name.decode(\"utf-8\")\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Fitting model: LightGBM_BAG_L2 ... Training model for up to 7.41s of the 7.37s of remaining time.\n",
      "\tFitting 4 child models (S1F1 - S1F4) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=3, gpus=0, memory=0.38%)\n",
      "\tWarning: Exception caused LightGBM_BAG_L2 to fail during training... Skipping this model.\n",
      "\t\t'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1904, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1844, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 856, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 165, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 288, in _fit\n",
      "    self._fit_folds(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 714, in _fit_folds\n",
      "    fold_fitting_strategy.after_all_folds_scheduled()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 651, in after_all_folds_scheduled\n",
      "    self.ray.init(**ray_init_args)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/worker.py\", line 1645, in init\n",
      "    _global_node = ray._private.node.Node(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 315, in __init__\n",
      "    self.start_ray_processes()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 1372, in start_ray_processes\n",
      "    resource_spec = self.get_resource_spec()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 550, in get_resource_spec\n",
      "    self._resource_spec = ResourceSpec(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/resource_spec.py\", line 215, in resolve\n",
      "    accelerator_manager.get_current_node_accelerator_type()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/accelerators/nvidia_gpu.py\", line 71, in get_current_node_accelerator_type\n",
      "    device_name = device_name.decode(\"utf-8\")\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Fitting model: RandomForestGini_BAG_L2 ... Training model for up to 2.98s of the 2.94s of remaining time.\n",
      "\t0.75\t = Validation score   (accuracy)\n",
      "\t0.69s\t = Training   runtime\n",
      "\t0.07s\t = Validation runtime\n",
      "Fitting model: RandomForestEntr_BAG_L2 ... Training model for up to 2.12s of the 2.08s of remaining time.\n",
      "\t0.75\t = Validation score   (accuracy)\n",
      "\t0.58s\t = Training   runtime\n",
      "\t0.06s\t = Validation runtime\n",
      "Fitting model: CatBoost_BAG_L2 ... Training model for up to 1.39s of the 1.35s of remaining time.\n",
      "\tFitting 4 child models (S1F1 - S1F4) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=3, gpus=0, memory=0.91%)\n",
      "\tWarning: Exception caused CatBoost_BAG_L2 to fail during training... Skipping this model.\n",
      "\t\t'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Detailed Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1904, in _train_and_save\n",
      "    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py\", line 1844, in _train_single\n",
      "    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 856, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py\", line 165, in _fit\n",
      "    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 288, in _fit\n",
      "    self._fit_folds(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py\", line 714, in _fit_folds\n",
      "    fold_fitting_strategy.after_all_folds_scheduled()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 651, in after_all_folds_scheduled\n",
      "    self.ray.init(**ray_init_args)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/worker.py\", line 1645, in init\n",
      "    _global_node = ray._private.node.Node(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 315, in __init__\n",
      "    self.start_ray_processes()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 1372, in start_ray_processes\n",
      "    resource_spec = self.get_resource_spec()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/node.py\", line 550, in get_resource_spec\n",
      "    self._resource_spec = ResourceSpec(\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/resource_spec.py\", line 215, in resolve\n",
      "    accelerator_manager.get_current_node_accelerator_type()\n",
      "  File \"/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/ray/_private/accelerators/nvidia_gpu.py\", line 71, in get_current_node_accelerator_type\n",
      "    device_name = device_name.decode(\"utf-8\")\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte\n",
      "Fitting model: WeightedEnsemble_L3 ... Training model for up to 39.05s of the -1.74s of remaining time.\n",
      "\tEnsemble Weights: {'RandomForestGini_BAG_L2': 1.0}\n",
      "\t0.75\t = Validation score   (accuracy)\n",
      "\t0.05s\t = Training   runtime\n",
      "\t0.0s\t = Validation runtime\n",
      "AutoGluon training complete, total runtime = 41.15s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 11.2 rows/s (4 batch size)\n",
      "TabularPredictor saved. To load, use: predictor = TabularPredictor.load(\"AutogluonModels/ag-20240709_183812\")\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "*** Summary of fit() ***\n",
      "Estimated performance of each model:\n",
      "                     model  score_val eval_metric  pred_time_val  fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order\n",
      "0  RandomForestEntr_BAG_L2       0.75    accuracy       0.351435  3.352069                0.064578           0.582486            2       True          7\n",
      "1  RandomForestGini_BAG_L2       0.75    accuracy       0.355773  3.458891                0.068916           0.689307            2       True          6\n",
      "2      WeightedEnsemble_L3       0.75    accuracy       0.356408  3.511482                0.000635           0.052592            3       True          8\n",
      "3  RandomForestEntr_BAG_L1       0.00    accuracy       0.065359  0.562550                0.065359           0.562550            1       True          2\n",
      "4    ExtraTreesGini_BAG_L1       0.00    accuracy       0.068117  0.601498                0.068117           0.601498            1       True          3\n",
      "5    ExtraTreesEntr_BAG_L1       0.00    accuracy       0.074413  0.689315                0.074413           0.689315            1       True          4\n",
      "6  RandomForestGini_BAG_L1       0.00    accuracy       0.078968  0.916220                0.078968           0.916220            1       True          1\n",
      "7      WeightedEnsemble_L2       0.00    accuracy       0.079788  1.017492                0.000820           0.101271            2       True          5\n",
      "Number of models trained: 8\n",
      "Types of models trained:\n",
      "{'StackerEnsembleModel_XT', 'StackerEnsembleModel_RF', 'WeightedEnsembleModel'}\n",
      "Bagging used: True  (with 4 folds)\n",
      "Multi-layer stack-ensembling used: True  (with 3 levels)\n",
      "Feature Metadata (Processed):\n",
      "(raw dtype, special dtypes):\n",
      "('int', []) : 2 | ['num', 'amount']\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/omar/anaconda3/envs/ag3.10/lib/python3.10/site-packages/autogluon/core/utils/plots.py:169: UserWarning: AutoGluon summary plots cannot be created because bokeh is not installed. To see plots, please do: \"pip install bokeh==2.0.1\"\n",
      "  warnings.warn('AutoGluon summary plots cannot be created because bokeh is not installed. To see plots, please do: \"pip install bokeh==2.0.1\"')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "*** End of fit() summary ***\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from autogluon.tabular import TabularPredictor\n",
    "\n",
    "df = pd.DataFrame(\n",
    "    [[1, 2, 0], [3, 4, 1], [5, 6, 0], [7, 8, 1]],\n",
    "    columns=[\"num\", \"amount\", \"target\"]\n",
    ")\n",
    "\n",
    "predictor = TabularPredictor(label=\"target\").fit(\n",
    "    train_data=df,\n",
    "    time_limit=60,\n",
    "    presets=\"best_quality\"\n",
    ")\n",
    "\n",
    "# output a summary of created models\n",
    "predictor.fit_summary()\n",
    "\n",
    "# evaluate best model from hyperparameter search\n",
    "performance = predictor.evaluate(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "ag3.10",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
